FROM golang:1.23-bullseye AS builder

WORKDIR /go/src/github.com/ory/hydra

RUN apt-get update && apt-get upgrade -y &&\
    mkdir -p ./internal/httpclient

COPY go.mod go.sum ./
COPY internal/httpclient/go.* ./internal/httpclient/

ENV CGO_ENABLED=1
ENV GO111MODULE on
ENV GOFLAGS -buildvcs=false

RUN go mod download

COPY . .
RUN go build -ldflags="-extldflags=-static" -tags sqlite,sqlite_omit_load_extension -o /usr/bin/hydra

#########################

FROM gcr.io/distroless/base-nossl-debian12:nonroot AS runner

COPY --from=builder /usr/bin/hydra /usr/bin/hydra
COPY --from=builder --chown=nonroot:nonroot /bin/sh /bin/sh

# Declare the standard ports used by hydra (4444 for public service endpoint, 4445 for admin service endpoint)
EXPOSE 4444 4445

ENTRYPOINT ["hydra"]
CMD ["serve", "all"]
